apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cpu-usage-alert
  namespace: kube-prometheus-stack
spec:
  groups:
  - name: pod-cpu.rules
    rules:
    - alert: HighPodCPUUsage
      expr: sum(rate(container_cpu_usage_seconds_total{image!="",pod!=""}[1m])) by (pod) > 0.8
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "CPU usage high on Pod {{ $labels.pod }}"
        description: "CPU usage of pod {{ $labels.pod }} is above 80% for more than 1 minute."
