apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  labels:
    app: springboot-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot
          image: phhieu16/coursecru_test-app:latest           # e.g. ghcr.io/you/your-app:1.0.0 or yourhub/user:tag
          imagePullPolicy: Never
          ports:
            - containerPort: 8080 
              name: http
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/course?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: "Hieu@123456"
            # ví dụ thêm profile và java opts
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: JAVA_OPTS
              value: -Xms256m -Xmx512m
